### ISSUE TITLE
Exceptions at first run after installation / 2

### ISSUE THREAD

**Issue by diti0023** [eclipse-platform/.github#116]
After installing (only PDE) via copy & apply (https://www.eclipse.org/setups/installer/?url=https://raw.githubusercontent.com/eclipse-platform/eclipse.platform.releng.aggregator/master/oomph/PlatformSDKConfiguration.setup&show=true) I get several errors when Eclipse starts.
The only change in the configuration was switching to Java 17.

JavaBuilder handling CoreException while building: org.eclipse.pde.api.tools.annotations (2x)
org.eclipse.core.runtime.CoreException: Failed to init ct.sym for /usr/lib/jvm/jre-17-openjdk-17.0.6.0.10-1.fc37.x86_64/lib/jrt-fs.jar
	at org.eclipse.jdt.internal.core.builder.ClasspathJrtWithReleaseOption.<init>(ClasspathJrtWithReleaseOption.java:79)
	at org.eclipse.jdt.internal.core.builder.ClasspathLocation.forJrtSystem(ClasspathLocation.java:169)
	at org.eclipse.jdt.internal.core.builder.NameEnvironment.computeClasspathLocations(NameEnvironment.java:333)
	at org.eclipse.jdt.internal.core.builder.NameEnvironment.<init>(NameEnvironment.java:63)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.initializeBuilder(JavaBuilder.java:644)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:182)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1020)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:247)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:392)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:395)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:506)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:454)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:536)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:196)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:289)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.io.FileNotFoundException: File /usr/lib/jvm/jre-17-openjdk-17.0.6.0.10-1.fc37.x86_64/lib/ct.sym does not exist
	at org.eclipse.jdt.internal.compiler.util.CtSym.init(CtSym.java:128)
	at org.eclipse.jdt.internal.compiler.util.CtSym.<init>(CtSym.java:122)
	at org.eclipse.jdt.internal.compiler.util.JRTUtil.lambda$1(JRTUtil.java:204)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
	at org.eclipse.jdt.internal.compiler.util.JRTUtil.getCtSym(JRTUtil.java:201)
	at org.eclipse.jdt.internal.core.builder.ClasspathJrtWithReleaseOption.<init>(ClasspathJrtWithReleaseOption.java:77)
	... 18 more

Failed to init ct.sym for /usr/lib/jvm/jre-17-openjdk-17.0.6.0.10-1.fc37.x86_64/lib/jrt-fs.jar
org.eclipse.core.runtime.CoreException: Failed to init ct.sym for /usr/lib/jvm/jre-17-openjdk-17.0.6.0.10-1.fc37.x86_64/lib/jrt-fs.jar
	at org.eclipse.jdt.internal.core.builder.ClasspathJrtWithReleaseOption.<init>(ClasspathJrtWithReleaseOption.java:79)
	at org.eclipse.jdt.internal.core.builder.ClasspathLocation.forJrtSystem(ClasspathLocation.java:169)
	at org.eclipse.jdt.internal.core.builder.NameEnvironment.computeClasspathLocations(NameEnvironment.java:333)
	at org.eclipse.jdt.internal.core.builder.NameEnvironment.<init>(NameEnvironment.java:63)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.initializeBuilder(JavaBuilder.java:644)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:182)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1020)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:247)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:392)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:395)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:506)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:454)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:536)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:196)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:289)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.io.FileNotFoundException: File /usr/lib/jvm/jre-17-openjdk-17.0.6.0.10-1.fc37.x86_64/lib/ct.sym does not exist
	at org.eclipse.jdt.internal.compiler.util.CtSym.init(CtSym.java:128)
	at org.eclipse.jdt.internal.compiler.util.CtSym.<init>(CtSym.java:122)
	at org.eclipse.jdt.internal.compiler.util.JRTUtil.lambda$1(JRTUtil.java:204)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
	at org.eclipse.jdt.internal.compiler.util.JRTUtil.getCtSym(JRTUtil.java:201)
	at org.eclipse.jdt.internal.core.builder.ClasspathJrtWithReleaseOption.<init>(ClasspathJrtWithReleaseOption.java:77)
	... 18 more
On my system ct.sym exists only for Java 11.

failed to read system packages for JavaSE-16 (etc. down to JavaSE-10)
org.eclipse.core.runtime.CoreException: Failed to init ct.sym for /usr/lib/jvm/java-17-openjdk-17.0.6.0.10-1.fc37.x86_64/lib/jrt-fs.jar
	at org.eclipse.jdt.internal.core.builder.ClasspathJrtWithReleaseOption.<init>(ClasspathJrtWithReleaseOption.java:79)
	at org.eclipse.jdt.internal.core.builder.ClasspathLocation.forJrtSystem(ClasspathLocation.java:169)
	at org.eclipse.pde.internal.core.TargetPlatformHelper.querySystemPackages(TargetPlatformHelper.java:410)
	at org.eclipse.pde.internal.core.TargetPlatformHelper.addEnvironmentProperties(TargetPlatformHelper.java:386)
	at org.eclipse.pde.internal.core.TargetPlatformHelper.getPlatformProperties(TargetPlatformHelper.java:371)
	at org.eclipse.pde.internal.core.MinimalState.initializePlatformProperties(MinimalState.java:238)
	at org.eclipse.pde.internal.core.PDEState.<init>(PDEState.java:68)
	at org.eclipse.pde.internal.core.PluginModelManager.initializeTable(PluginModelManager.java:616)
	at org.eclipse.pde.internal.core.PluginModelManager.targetReloaded(PluginModelManager.java:541)
	at org.eclipse.pde.core.target.LoadTargetDefinitionJob.resetPlatform(LoadTargetDefinitionJob.java:184)
	at org.eclipse.pde.core.target.LoadTargetDefinitionJob.runInWorkspace(LoadTargetDefinitionJob.java:145)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.oomph.util.pde.TargetPlatformUtil.activateTargetDefinition(TargetPlatformUtil.java:156)
	at org.eclipse.oomph.targlets.internal.core.TargletContainer.forceUpdate(TargletContainer.java:905)
	at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl$4.run(TargletTaskImpl.java:1232)
	at org.eclipse.oomph.util.pde.TargetPlatformUtil.runWithTargetPlatformService(TargetPlatformUtil.java:120)
	at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl.perform(TargletTaskImpl.java:1092)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2382)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2407)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
	at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
	at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.io.FileNotFoundException: File /usr/lib/jvm/java-17-openjdk-17.0.6.0.10-1.fc37.x86_64/lib/ct.sym does not exist
	at org.eclipse.jdt.internal.compiler.util.CtSym.init(CtSym.java:128)
	at org.eclipse.jdt.internal.compiler.util.CtSym.<init>(CtSym.java:122)
	at org.eclipse.jdt.internal.compiler.util.JRTUtil.lambda$1(JRTUtil.java:204)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
	at org.eclipse.jdt.internal.compiler.util.JRTUtil.getCtSym(JRTUtil.java:201)
	at org.eclipse.jdt.internal.core.builder.ClasspathJrtWithReleaseOption.<init>(ClasspathJrtWithReleaseOption.java:77)
	... 27 more

Failed to init ct.sym for /usr/lib/jvm/java-17-openjdk-17.0.6.0.10-1.fc37.x86_64/lib/jrt-fs.jar
java.io.FileNotFoundException: File /usr/lib/jvm/java-17-openjdk-17.0.6.0.10-1.fc37.x86_64/lib/ct.sym does not exist
	at org.eclipse.jdt.internal.compiler.util.CtSym.init(CtSym.java:128)
	at org.eclipse.jdt.internal.compiler.util.CtSym.<init>(CtSym.java:122)
	at org.eclipse.jdt.internal.compiler.util.JRTUtil.lambda$1(JRTUtil.java:204)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
	at org.eclipse.jdt.internal.compiler.util.JRTUtil.getCtSym(JRTUtil.java:201)
	at org.eclipse.jdt.internal.core.builder.ClasspathJrtWithReleaseOption.<init>(ClasspathJrtWithReleaseOption.java:77)
	at org.eclipse.jdt.internal.core.builder.ClasspathLocation.forJrtSystem(ClasspathLocation.java:169)
	at org.eclipse.pde.internal.core.TargetPlatformHelper.querySystemPackages(TargetPlatformHelper.java:410)
	at org.eclipse.pde.internal.core.TargetPlatformHelper.addEnvironmentProperties(TargetPlatformHelper.java:386)
	at org.eclipse.pde.internal.core.TargetPlatformHelper.getPlatformProperties(TargetPlatformHelper.java:371)
	at org.eclipse.pde.internal.core.MinimalState.initializePlatformProperties(MinimalState.java:238)
	at org.eclipse.pde.internal.core.PDEState.<init>(PDEState.java:68)
	at org.eclipse.pde.internal.core.PluginModelManager.initializeTable(PluginModelManager.java:616)
	at org.eclipse.pde.internal.core.PluginModelManager.targetReloaded(PluginModelManager.java:541)
	at org.eclipse.pde.core.target.LoadTargetDefinitionJob.resetPlatform(LoadTargetDefinitionJob.java:184)
	at org.eclipse.pde.core.target.LoadTargetDefinitionJob.runInWorkspace(LoadTargetDefinitionJob.java:145)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.oomph.util.pde.TargetPlatformUtil.activateTargetDefinition(TargetPlatformUtil.java:156)
	at org.eclipse.oomph.targlets.internal.core.TargletContainer.forceUpdate(TargletContainer.java:905)
	at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl$4.run(TargletTaskImpl.java:1232)
	at org.eclipse.oomph.util.pde.TargetPlatformUtil.runWithTargetPlatformService(TargetPlatformUtil.java:120)
	at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl.perform(TargletTaskImpl.java:1092)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2382)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2407)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
	at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
	at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by vogella** [comment]
@merks sounds like this is Oomph related, please have a look.

**Comment by merks** [comment]
It doesn't actually look Oomph related.  It looks like JDT is having trouble with the specific JDK on the user's machine and that indirectly causes problems for PDE using JDT and that further indirectly causes problems for Oomph using PDE.  Better that JDT have a look.

**Comment by iloveeclipse** [comment]
Your have no proper java 17 **JDK** installed, only **JRE**. That is not sufficient for Java development.

**Comment by vogella** [comment]
I assumed the Oomph setup would also provide a JDK

**Comment by merks** [comment]
@vogella 

The installer lets the user choose whatever JRE/JDK they want (for running the installation/IDE), including choices on their machine as well as compatible JustJ JREs (which definitely do work correctly for JDT's purposes).

@iloveeclipse 

I was not aware that JDT required a JDK, but if that's the case, it might provide a more informative failure message.

Should we close this then?

**Comment by iloveeclipse** [comment]
@merks : yes, JDT and so everything that requires JDT (like PDE) require JDK, **not** JRE. 
Regarding a better message - well, contributions are welcome :-)

**Comment by jukzi** [comment]
confusing that open_jdk_ does not count as an jdk ;-)
requires to reed carefully "_jre_-17-openjdk"

**Comment by diti0023** [comment]
Found out how Fedora Linux actually handles JDK ...
But still:
Failed to init ct.sym for /usr/lib/jvm/java-17-openjdk-17.0.6.0.10-1.fc37.x86_64/lib/jrt-fs.jar

java.io.FileNotFoundException: File /usr/lib/jvm/java-17-openjdk-17.0.6.0.10-1.fc37.x86_64/lib/ct.sym does not exist

$ l /usr/lib/jvm/java-17-openjdk-17.0.6.0.10-1.fc37.x86_64/lib/ct.sym
-rw-r--r-- 1 root root 8301486 Jan 26 05:13 /usr/lib/jvm/java-17-openjdk-17.0.6.0.10-1.fc37.x86_64/lib/ct.sym

Even restarting Eclipse didn't help.

**Comment by iloveeclipse** [comment]
@diti0023 : you have to setup your Eclipse using **JDK** not JRE, so please just throw away the current install (I have no idea in which state it is) and if you install Eclipse, point to /usr/lib/jvm/java-17-openjdk-17 and NOT to the JRE.

**Comment by diti0023** [comment]
@iloveeclipse: What I meant in my post above: I wasn't aware how **Fedora** behaves at this point, and that the Error Log is not cleared. So now, after really installing **JDK**, install and build are OK. Thanks.
