### ISSUE TITLE
No repository found containing: osgi.bundle,org.eclipse.jdt.junit.source,3.16.0.v20230417-2128

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/.github#118]
Oomphing platform fails with:

```
Mirrored 22 artifacts from https://download.eclipse.org/reddeer/releases/latest/ at 143kb/s
Collected 22 artifacts for https://download.eclipse.org/reddeer/releases/latest in 6.494s
An error was detected while performing the engine operation and the changes are being rolled back. See the log for details.
ERROR: org.eclipse.pde.core code=0 Problems occurred while resolving the target contents
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:296)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.activateTargetDefinition(TargetPlatformUtil.java:151)
  at org.eclipse.oomph.targlets.internal.core.TargletContainer.forceUpdate(TargletContainer.java:905)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl$4.run(TargletTaskImpl.java:1232)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.runWithTargetPlatformService(TargetPlatformUtil.java:120)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl.perform(TargletTaskImpl.java:1092)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2382)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2407)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.engine code=4 An error occurred while collecting items to be installed
    ERROR: org.eclipse.equinox.p2.engine code=0 session context was:(profile=C__Users_JKubitz_eclipseDev_platform-sdk20230418_Latest-d60b8891c8771426a23024bce0f27f47b3e57263, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
    ERROR: org.eclipse.equinox.p2.artifact.repository code=0 No repository found containing: osgi.bundle,org.eclipse.jdt.junit.source,3.16.0.v20230417-2128

Took 1408 seconds.

```

**Comment by merks** [comment]
It looks like you or download.eclipse.org is having network problems today.  You could report a p2 problem, but this type of problem has happened before.  It happens when the content metadata that p2 sees does not match the artifact metadata and goes away after a few minutes or after the network problem goes away.  In any case, it can't be fixed anywhere except in p2.

**Comment by jukzi** [comment]
confirm: retry and the issue was gone.

**Comment by merks** [comment]
@jukzi 

It's super annoying nevertheless.  Sometimes I get a failure because "the artifact already exists in the repo" where I think, yes, so please use it.  😜
