### ISSUE TITLE
OSGI-INF xml "File not found" Errors

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/.github#147]
With a today (M3) OOmphed Eclipse Development Environment (https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md) i see multiple "File not found" Errors right after starting

![image](https://github.com/eclipse-platform/.github/assets/51790620/595d38d2-7b3c-4d64-bd24-b26d3c5c7de5)

for example:

```
java.io.FileNotFoundException: \org.eclipse.equinox.p2.core\OSGI-INF\org.eclipse.equinox.p2.core.eventbus.xml (Das System kann den angegebenen Pfad nicht finden)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at org.eclipse.core.internal.filesystem.local.LocalFile.openInputStream(LocalFile.java:453)
	at org.eclipse.wst.sse.core.internal.FileBufferModelManager.detectContentType(FileBufferModelManager.java:596)
	at org.eclipse.wst.sse.core.internal.FileBufferModelManager$FileBufferMapper.bufferCreated(FileBufferModelManager.java:344)
	at org.eclipse.core.internal.filebuffers.TextFileBufferManager$11.run(TextFileBufferManager.java:775)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.filebuffers.TextFileBufferManager.fireBufferCreated(TextFileBufferManager.java:772)
	at org.eclipse.core.internal.filebuffers.TextFileBufferManager.connect(TextFileBufferManager.java:131)
	at org.eclipse.pde.ds.internal.annotations.AnnotationVisitor.processComponent(AnnotationVisitor.java:372)
	at org.eclipse.pde.ds.internal.annotations.AnnotationVisitor.visit(AnnotationVisitor.java:246)
	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:482)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3254)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3325)
	at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:258)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3254)
	at org.eclipse.pde.ds.internal.annotations.AnnotationProcessor.acceptAST(AnnotationProcessor.java:74)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1008)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:692)
	at org.eclipse.jdt.core.dom.ASTParser.createASTs(ASTParser.java:954)
	at org.eclipse.pde.ds.internal.annotations.DSAnnotationCompilationParticipant.processAnnotations(DSAnnotationCompilationParticipant.java:714)
	at org.eclipse.pde.ds.internal.annotations.DSAnnotationCompilationParticipant.processAnnotations(DSAnnotationCompilationParticipant.java:650)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.processAnnotations(AbstractImageBuilder.java:668)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:375)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:79)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:273)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:188)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1079)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:594)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:483)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$6.run(SetupTaskPerformer.java:3909)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by jukzi** [comment]
not platform - see
https://git.eclipse.org/c/sourceediting/webtools.sourceediting.git/diff/?id=709c16bd4a51de7bff0d6f82b186a6e6a0e2ffb9

**Comment by merks** [comment]
Note that the actual file is **generated** and not committed to the Git repository:

![image](https://github.com/eclipse-platform/.github/assets/208716/9852a876-93b9-432e-b50d-d04fd3423234)

So it will initially not exist.   So these references in the MANIFEST.MF will be "broken" until they have been generated:
```
Service-Component: OSGI-INF/org.eclipse.equinox.p2.core.eventbus.xml,
 OSGI-INF/org.eclipse.equinox.p2.di.agentProvider.xml
```

 @HannesWell  @laeubi 

Probably this is an issue that PDE needs to investigate....

**Comment by merks** [comment]
Or it's WTP's fault, making it less likely to be fixed any time soon.  😱

**Comment by iloveeclipse** [comment]
> Or it's WTP's fault, making it less likely to be fixed any time soon. 😱

Why that? It was just committed, so the committer is there and [one can comment on the ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=582302).

**Comment by merks** [comment]
It was just a theory based on lack of response here:

https://github.com/eclipse-orbit/orbit-simrel/issues/9

and without having looked at it as being a recent commit.

**Comment by HannesWell** [comment]
> So it will initially not exist. So these references in the MANIFEST.MF will be "broken" until they have been generated:
> 
> ```
> Service-Component: OSGI-INF/org.eclipse.equinox.p2.core.eventbus.xml,
>  OSGI-INF/org.eclipse.equinox.p2.di.agentProvider.xml
> ```
> 
> @HannesWell @laeubi
> 
> Probably this is an issue that PDE needs to investigate....

It is right that the file does not exist initially, but I have never noticed any error like this, altough use not-commited DS files in many occasions.

I have not fully understood what was now causing this and why this was closed, but I Jörg certainly knows what he is doing. :)

**Comment by jukzi** [comment]
> why this was closed

this is now https://bugs.eclipse.org/bugs/show_bug.cgi?id=582302

**Comment by jukzi** [comment]
related commit to fix this: https://git.eclipse.org/c/sourceediting/webtools.sourceediting.git/commit/?id=fac0aa24a44eb667ce3697c7b32718b9cb72abe8
