### ISSUE TITLE
Update SDK fails (with Oomph)

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/.github#150]
I tried to upgrade to the latest development SDK but it fails

```
Committing the provisioning operation.
ERROR: org.eclipse.oomph.targlets.core code=0 Resolution problems
  at org.eclipse.oomph.targlets.internal.core.TargletContainer.forceUpdate(TargletContainer.java:919)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl$4.run(TargletTaskImpl.java:1232)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.runWithTargetPlatformService(TargetPlatformUtil.java:120)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl.perform(TargletTaskImpl.java:1092)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2453)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2478)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.oomph.targlets.core code=0 Problems resolving composed target 'eclipse-sdk-prereqs'
    ERROR: org.eclipse.pde.core code=0 Problems occurred while resolving the target contents
      ERROR: org.eclipse.pde.core code=0 Problems loading repositories
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.junit 4.13.2.v20230809-1000
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.junit.source 4.13.2.v20230809-1000
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.apache.lucene.core 9.7.0.v20230703-0758
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.apache.lucene.analysis-smartcn 9.7.0.v20230703-0758
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.apache.lucene.analysis-common 9.7.0.v20230703-0758
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.apache.lucene.core.source 9.7.0.v20230703-0758
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.apache.lucene.analysis-smartcn.source 9.7.0.v20230703-0758
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.apache.lucene.analysis-common.source 9.7.0.v20230703-0758
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.hamcrest.core 2.2.0.v20230809-1000
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.hamcrest.core.source 2.2.0.v20230809-1000
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.jdom 1.1.3.v20230812-1600
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.jdom.source 1.1.3.v20230812-1600
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit com.sun.jna 5.13.0.v20230812-1000

Took 25 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.
```

@merks any idea whats going wrong here?

**Comment by merks** [comment]
Hmmm.  Some problem locating artifacts...

If you want to update to work on the 4.30 stream, updating doesn't really work quite properly until I commit the catalog changes tomorrow morning.  In the meantime, you can do what's described here and that will also likely avoid the problem above:

https://github.com/eclipse-platform/eclipse.platform/pull/591#issuecomment-1713908738

**Comment by fedejeanne** [comment]
@merks I was just about to answer to your comment. I tried that and got this error after I restarted Eclipse:

```java
Collected 151 artifacts for https://download.eclipse.org/eclipse/updates/4.30-I-builds in 44.098s
An error was detected while performing the engine operation and the changes are being rolled back. See the log for details.
ERROR: org.eclipse.equinox.p2.engine code=4 An error occurred while collecting items to be installed
  at org.eclipse.oomph.targlets.internal.core.TargletContainer.forceUpdate(TargletContainer.java:919)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl$4.run(TargletTaskImpl.java:1232)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.runWithTargetPlatformService(TargetPlatformUtil.java:120)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl.perform(TargletTaskImpl.java:1092)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2453)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2478)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.engine code=0 session context was:(profile=D__dev_eclipse-contributors-experimental_ws-ccda9bedb12d140d001ded00b7609b64c6fa3d42, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
  ERROR: org.eclipse.equinox.p2.artifact.repository code=1201 The artifact is already available in the repository file:/C:/Users/myuser/.p2/pool/.
```

**Comment by laeubi** [comment]
> updating doesn't really work quite properly until I commit the catalog changes tomorrow morning

It might then be better to wait until then I think... I'm just curious about what is the meant workflow, should really everyone "freeze" (e.g. better not even start the SDK) from RC1 to final release? I remember I always getting some intermediate problem there (API tools, Oomph setup, builds...) what is quite annoying.

**Comment by merks** [comment]
Yes, it's quite annoying.   I keep meaning to provide something better for that one week period when the release is not public, but the master stream is open for the next release.    Those two redirections used in some conditional way is pretty much the only way...

The annoying "artifact is already available" issue always goes away if you simply perform the task again.  Again, it would seem better to me if p2, rather than failing, would just use the artifact that's suddenly already unexpectedly there.  I have no idea how to reproduce that problem, but it happens to me too from time to time; probably because I have so many IDEs open at once...

**Comment by fedejeanne** [comment]
> The annoying "artifact is already available" issue always goes away if you simply perform the task again

Thank you, that did the trick!

>  I have no idea how to reproduce that problem, but it happens to me too from time to time; **probably because I have so many IDEs open at once...**

I had only 1 IDE opened and the error showed up anyway so I wouldn't peg it on that :-\

**Comment by merks** [comment]
@fedejeanne 

I have no good theory for why an artifact file would be present but the artifact metadata doesn't know that's it's present so tries to download it again...

**Comment by fedejeanne** [comment]
@merks sadly, neither do I 😕 

I remember having seen the same error while working with 2 bundle-pools: I wanted to move the default one to another disk to free-up some space but I finally gave up and reverted everything back to their defaults because I had lots of troubles with the approach.

**Comment by laeubi** [comment]
@merks I now did update al repositories, installed all updates and restarted and tried again but still getting:

```
Fetching org.eclipse.sdk.examples_root_4.30.0.v20230917-1800 from https://download.eclipse.org/eclipse/updates/4.30-I-builds/I20230917-1800/binary/ (150B)
Fetching org.eclipse.platform_root_4.30.0.v20230917-1800 from https://download.eclipse.org/eclipse/updates/4.30-I-builds/I20230917-1800/binary/ (196B)
Fetching org.eclipse.rcp_root_4.30.0.v20230917-1800 from https://download.eclipse.org/eclipse/updates/4.30-I-builds/I20230917-1800/binary/ (20,25kB)
Mirrored 3 artifacts from https://download.eclipse.org/eclipse/updates/4.30-I-builds/I20230917-1800/ at 12kb/s
Collected 4 artifacts for https://download.eclipse.org/eclipse/updates/4.30-I-builds in 1.204s
Preparing to commit the provisioning operation.
Committing the provisioning operation.
ERROR: org.eclipse.oomph.targlets.core code=0 Resolution problems
  at org.eclipse.oomph.targlets.internal.core.TargletContainer.forceUpdate(TargletContainer.java:919)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl$4.run(TargletTaskImpl.java:1232)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.runWithTargetPlatformService(TargetPlatformUtil.java:120)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl.perform(TargletTaskImpl.java:1092)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2453)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2478)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.oomph.targlets.core code=0 Problems resolving composed target 'eclipse-sdk-prereqs'
    ERROR: org.eclipse.pde.core code=0 Problems occurred while resolving the target contents
      ERROR: org.eclipse.pde.core code=0 Problems loading repositories
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.junit 4.13.2.v20230809-1000
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.junit.source 4.13.2.v20230809-1000
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.apache.lucene.core 9.7.0.v20230703-0758
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.apache.lucene.analysis-smartcn 9.7.0.v20230703-0758
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.apache.lucene.analysis-common 9.7.0.v20230703-0758
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.apache.lucene.core.source 9.7.0.v20230703-0758
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.apache.lucene.analysis-smartcn.source 9.7.0.v20230703-0758
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.apache.lucene.analysis-common.source 9.7.0.v20230703-0758
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.hamcrest.core 2.2.0.v20230809-1000
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.hamcrest.core.source 2.2.0.v20230809-1000
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.jdom 1.1.3.v20230812-1600
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.jdom.source 1.1.3.v20230812-1600
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit com.sun.jna 5.13.0.v20230812-1000
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.orbit.xml-apis-ext 1.0.0.v20230815-1152
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.orbit.xml-apis-ext.source 1.0.0.v20230815-1152

Took 62 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.
```

**Comment by merks** [comment]
It's failing resolving the *.target from based on the message `Problems resolving composed target 'eclipse-sdk-prereqs'`.    The aggr git repository itself is pulled to the latest state?

**Comment by laeubi** [comment]
So should I remove the `eclipse-sdk-prereqs` project maybe?

> The aggr git repository itself is pulled to the latest state?

I have updated all repositories to the latest commit (even though this often changes fast) as of today.

**Comment by merks** [comment]
In the past there was a problem that the *.target file appeared in two places in the workspace.  Then I added filters such that this is no longer the case:

![image](https://github.com/eclipse-platform/.github/assets/208716/a6fc6191-05f0-4429-91d9-2b26d8764f69)

This is why I asked about the state of your clone.

Every release I just create a brand new fresh installation with a brand new fresh workspace and clones.  (I do that also as test that it all actually works.)

**Comment by laeubi** [comment]
> Every release I just create a brand new fresh installation with a brand new fresh workspace and clones.

The problem is that one looses all local state then (as far as I know) and reconfigure all the git repositories is not fun :-\
Maybe I missed the filter part because of only upgrading the existing IDE... at least it seem to work now (again).
