### ISSUE TITLE
"Perform setup tasks" fails

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/.github#154]
I updated all my repos in the WS to the latest status and ran _Help > Perform setup tasks_ and got this error:

```java
Updating Git status for repository eclipse.jdt.ui
ERROR: org.eclipse.oomph.targlets.core code=0 Resolution problems
  at org.eclipse.oomph.targlets.internal.core.TargletContainer.forceUpdate(TargletContainer.java:919)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl$4.run(TargletTaskImpl.java:1232)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.runWithTargetPlatformService(TargetPlatformUtil.java:120)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl.perform(TargletTaskImpl.java:1092)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2453)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2478)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.oomph.targlets.core code=0 Problems resolving composed target 'eclipse-sdk-prereqs'
    ERROR: org.eclipse.pde.core code=0 Problems occurred while resolving the target contents
      ERROR: org.eclipse.pde.core code=0 Problems loading repositories
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.orbit.xml-apis-ext 1.0.0.v20230815-1152
        ERROR: org.eclipse.pde.core code=0 Unable to locate installable unit org.eclipse.orbit.xml-apis-ext.source 1.0.0.v20230815-1152
```

## What I did for each repo in my WS (in the console):

```sh
# Sync fork with GitHub-CLI
gh repo sync fedejeanne/<repo_name> -b master

# Switch to master, discard uncommitted/unstaged changes with '-f'
git checkout master -f

# Remove all local changes
git reset --hard

# PULL
git pull
```

These are my repos **after** performing the setup tasks:
![image](https://github.com/eclipse-platform/.github/assets/2205684/937a7166-cbf6-4180-840e-89585db8b3b8)

Notice that `eclipse.jdt.ui` has local changes after performing the setup tasks, but they are irrelevant:
![image](https://github.com/eclipse-platform/.github/assets/2205684/fa389158-cfe0-4bd9-b017-0440a5390f85)

@merks  do you thing this is related to #150 ?

**Comment by laeubi** [comment]
For me it helped to remove the `eclipse-sdk-prereqs` project from the workspace.

**Comment by fedejeanne** [comment]
> For me it helped to remove the `eclipse-sdk-prereqs` project from the workspace.

You mean this one?

![image](https://github.com/eclipse-platform/.github/assets/2205684/d7324692-a47c-46bd-b475-339363e75e09)

I closed it and tried again, but got this other error:

```java
Committing the provisioning operation.
ERROR: org.eclipse.oomph.targlets.core code=0 Resolution problems
  at org.eclipse.oomph.targlets.internal.core.TargletContainer.forceUpdate(TargletContainer.java:919)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl$4.run(TargletTaskImpl.java:1232)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.runWithTargetPlatformService(TargetPlatformUtil.java:120)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl.perform(TargletTaskImpl.java:1092)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2453)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2478)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.oomph.targlets.core code=0 Problems resolving composed target 'eclipse-sdk-prereqs'
    ERROR: org.eclipse.oomph.targlets.core code=0 A target definition named 'eclipse-sdk-prereqs' does not exist.

```

**Comment by merks** [comment]
The dirty project is because it has an m2e nature that was causing errors.

If you do this, is there a single eclipse-sdk-prereqs.target resource?

![image](https://github.com/eclipse-platform/.github/assets/208716/adb6a680-1c90-417c-8873-f0dca592a53c)

**Comment by laeubi** [comment]
> I closed it and tried again, but got this other error:

I literally removed it from the workspace (but not delete the contents on disk)

**Comment by merks** [comment]
And I don't get the comment about removing eclipse-sdk-prereqs because the targlet compose that target platform so at least one version of it must be present in the workspace as I understand it.

**Comment by fedejeanne** [comment]
> The dirty project is because it has an m2e nature that was causing errors.
> 
> If you do this, is there a single eclipse-sdk-prereqs.target resource?
> 
> ![image](https://user-images.githubusercontent.com/208716/269185324-adb6a680-1c90-417c-8873-f0dca592a53c.png)

I reopened the project and I only see this one:

![image](https://github.com/eclipse-platform/.github/assets/2205684/4eaa284e-352f-4252-98fe-8cce3d2128c0)

**Comment by merks** [comment]
That looks correct.  PDE also sometimes has caching problems.  :-(  

If all else fails, you can delete this and save it:

![image](https://github.com/eclipse-platform/.github/assets/208716/b8cdb0e3-e149-49e6-ac35-e3ae69dd6b8a)

**Comment by merks** [comment]
You can also try to open the *.target in the target editor and let it finish resolving.  That might refresh the PDE cache if that's the problem.

**Comment by merks** [comment]
Not that it's helpful, but this does "just work for me":

![image](https://github.com/eclipse-platform/.github/assets/208716/b8174249-bb3d-4b32-a1fa-a0e95d27a6bd)

**Comment by fedejeanne** [comment]
> You can also try to open the *.target in the target editor and let it finish resolving. That might refresh the PDE cache if that's the problem.

Thank you, that did the trick! 

Closing this issue.

**Comment by merks** [comment]
The *.target doesn't have a sequenceNumber and it's possible that incrementing such a thing would help PDE update the cache.  E.g., in Oomph we have this:
```
<target name="Generated from Oomph" sequenceNumber="134">
```
and we increment it when we regenerate it....

@HannesWell 

Do you think such a thing would help?

**Comment by HannesWell** [comment]
> Do you think such a thing would help?

It could help, but I don't know this for sure since I never checked for what that number is used for.

In general PDE should be smart enough to detect changes even without such hints, e.g. based on the File hash or changes in the XML tree.
