### ISSUE TITLE
Build failure 'Cannot invoke org.eclipse.pde.internal.core.schema.SchemaProvider.createSchema" on fresh SDK installation

### ISSUE THREAD

**Issue by kthoms** [eclipse-platform/.github#167]
I have just set up a fresh SDK development environment using the Oomph Auto-Install according to the Contribution guideline.

This worked mostly well, but at the very end a Build Problem dialog appears.
![Bildschirm­foto 2023-11-01 um 09 40 54](https://github.com/eclipse-platform/.github/assets/265597/fb237a8d-e375-4870-9853-45d524088271)

Details show that for multiple project the same error appears:

```
Errors running builder 'Extension Point Schema Builder' on project 'org.eclipse.core.expressions'.
Cannot invoke "org.eclipse.pde.internal.core.schema.SchemaProvider.createSchema(org.eclipse.pde.internal.core.ischema.ISchemaDescriptor, String)" because "this.schemaProvider" is null
```

![Bildschirm­foto 2023-11-01 um 09 41 42](https://github.com/eclipse-platform/.github/assets/265597/b263e73e-4448-495e-8394-533f61cdc9fc)

The error does not look as it harms the setup, however, it should not appear.

**Comment by laeubi** [comment]
@kthoms any chance there is an entry in the Error Log with a full stacktrace?

**Comment by kthoms** [comment]
```
java.lang.NullPointerException: Cannot invoke "org.eclipse.pde.internal.core.schema.SchemaProvider.createSchema(org.eclipse.pde.internal.core.ischema.ISchemaDescriptor, String)" because "this.schemaProvider" is null
	at org.eclipse.pde.internal.core.schema.SchemaInclude.getIncludedSchema(SchemaInclude.java:96)
	at org.eclipse.pde.internal.core.builders.SchemaErrorReporter.validateInclude(SchemaErrorReporter.java:308)
	at org.eclipse.pde.internal.core.builders.SchemaErrorReporter.validate(SchemaErrorReporter.java:121)
	at org.eclipse.pde.internal.core.builders.XMLErrorReporter.validateContent(XMLErrorReporter.java:379)
	at org.eclipse.pde.internal.core.builders.ExtensionPointSchemaBuilder.compileFile(ExtensionPointSchemaBuilder.java:140)
	at org.eclipse.pde.internal.core.builders.ExtensionPointSchemaBuilder.compileSchemasIn(ExtensionPointSchemaBuilder.java:193)
	at org.eclipse.pde.internal.core.builders.ExtensionPointSchemaBuilder.compileSchemasIn(ExtensionPointSchemaBuilder.java:191)
	at org.eclipse.pde.internal.core.builders.ExtensionPointSchemaBuilder.compileSchemasIn(ExtensionPointSchemaBuilder.java:191)
	at org.eclipse.pde.internal.core.builders.ExtensionPointSchemaBuilder.compileSchemasIn(ExtensionPointSchemaBuilder.java:191)
	at org.eclipse.pde.internal.core.builders.ExtensionPointSchemaBuilder.build(ExtensionPointSchemaBuilder.java:96)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1079)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:594)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:483)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$6.run(SetupTaskPerformer.java:3909)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
	
```
