### ISSUE TITLE
"Perform Setup Tasks" does nothing

### ISSUE THREAD

**Issue by Wittmaxi** [eclipse-platform/.github#217]
When I press `Help -> Perform Setup Tasks`, no window is displayed, no progress bar is shown.

The error log shows one error which seems related:
```
java.lang.LinkageError: loader constraint violation: loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @3ce20102 wants to load class org.apache.hc.client5.http.impl.classic.HttpClientBuilder. A different class with the same name was previously loaded by org.eclipse.osgi.internal.loader.EquinoxClassLoader @6a7e5473. (org.apache.hc.client5.http.impl.classic.HttpClientBuilder is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @6a7e5473, parent loader 'platform')
	at org.eclipse.ecf.internal.provider.filetransfer.httpclient5.Activator.getHttpClientFactory(Activator.java:247)
	at org.eclipse.ecf.internal.provider.filetransfer.httpclient5.Activator.registerHttpClient(Activator.java:290)
	at org.eclipse.ecf.internal.provider.filetransfer.httpclient5.Activator.getRetrieveHttpClient(Activator.java:281)
	at org.eclipse.ecf.provider.filetransfer.httpclient5.HttpClientRetrieveFileTransferFactory.newInstance(HttpClientRetrieveFileTransferFactory.java:25)
	at org.eclipse.ecf.internal.provider.filetransfer.Activator.getFileTransfer(Activator.java:614)
	at org.eclipse.ecf.provider.filetransfer.retrieve.MultiProtocolRetrieveAdapter.sendRetrieveRequest(MultiProtocolRetrieveAdapter.java:94)
	at org.eclipse.oomph.setup.internal.core.util.ECFURIHandlerImpl$InputStreamConnectionHandler.sendConnectionRequest(ECFURIHandlerImpl.java:1943)
	at org.eclipse.oomph.setup.internal.core.util.ECFURIHandlerImpl$ConnectionHandler.process(ECFURIHandlerImpl.java:1642)
	at org.eclipse.oomph.setup.internal.core.util.ECFURIHandlerImpl.createInputStream(ECFURIHandlerImpl.java:321)
	at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createInputStream(ExtensibleURIConverterImpl.java:358)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1314)
	at org.eclipse.oomph.setup.internal.core.util.SetupCoreUtil.handleArchiveRedirection(SetupCoreUtil.java:696)
	at org.eclipse.oomph.setup.internal.core.util.SetupCoreUtil.configureResourceSet(SetupCoreUtil.java:474)
	at org.eclipse.oomph.setup.internal.core.util.SetupCoreUtil.configureResourceSet(SetupCoreUtil.java:268)
	at org.eclipse.oomph.setup.internal.core.util.SetupCoreUtil.createResourceSet(SetupCoreUtil.java:262)
	at org.eclipse.oomph.setup.ui.wizards.SetupWizard.<init>(SetupWizard.java:182)
	at org.eclipse.oomph.setup.ui.wizards.SetupWizard.<init>(SetupWizard.java:174)
	at org.eclipse.oomph.setup.ui.wizards.SetupWizard$Updater.<init>(SetupWizard.java:1761)
	at org.eclipse.oomph.setup.ui.wizards.SetupWizard$Updater$1.<init>(SetupWizard.java:1807)
	at org.eclipse.oomph.setup.ui.wizards.SetupWizard$Updater.perform(SetupWizard.java:1807)
	at org.eclipse.oomph.setup.presentation.handlers.PerformHandler.run(PerformHandler.java:52)
	at org.eclipse.oomph.setup.presentation.handlers.AbstractDropdownItemHandler.execute(AbstractDropdownItemHandler.java:51)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:277)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:98)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:299)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:233)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:174)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:165)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:204)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommandInContext(LegacyHandlerService.java:436)
	at org.eclipse.ui.internal.quickaccess.providers.CommandElement.execute(CommandElement.java:60)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4059)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3677)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
```

I have already seen and applied the advice of https://github.com/eclipse-platform/.github/issues/154. I don't believe it is related and the error message is different

**Comment by merks** [comment]
I tried it now and it worked, installing the latest updates, and restarted and then it still worked okay.

Which versions of ECF are installed for you?

![image](https://github.com/eclipse-platform/.github/assets/208716/3562d756-6259-4db5-b4f4-b5f48cf66a3d)

And which versions of the Apache http libraries?

![image](https://github.com/eclipse-platform/.github/assets/208716/bd84eeb0-6c4a-4323-8cf0-afebc723b2e5)

**Comment by laeubi** [comment]
@Wittmaxi can you share the Build ID from the help?

**Comment by Wittmaxi** [comment]
@laeubi 
Version: 2024-06 RC1 (4.32.0 RC1)
Build id: 20240530-0607

@merks 
![grafik](https://github.com/eclipse-platform/.github/assets/16443184/78a7f17c-8396-4148-ab66-0cea454672df)
![grafik](https://github.com/eclipse-platform/.github/assets/16443184/976c763f-dc49-43cc-b03b-9aba155ca780)

I am not really sure what these libraries do and what they mean, so I just shot those screenshots without understanding what is happening

**Comment by merks** [comment]
I guess you didn't use the full SDK setup:

https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#creating-an-eclipse-development-environment

Also, it sounds like you installed one of the EPP packages, not the Eclipse SDK itself.  Generally one should install the Eclipse SDK product so that you're "on the same page" as everyone else and are regularly "eating your own dog food", i.e., this product and version:

![image](https://github.com/eclipse-platform/.github/assets/208716/7a3e36b8-c578-498b-bcb7-0e2ca2bacb45)

That way, on a semi-regular basis you can update to the latest I-build.

I'm not really sure what's gone wrong with your installation with strange class loader conflicts.   The path of least resistance is to create a new one setup...

**Comment by Wittmaxi** [comment]
@merks looks like that is the next step then... Thank you :)

**Comment by merks** [comment]
Sorry I couldn't actually fix the problem.  It's a new one I've never seem before!!

**Comment by Wittmaxi** [comment]
@merks no worries :)
