### ISSUE TITLE
Windows I-Builds fail since I20240808-1800

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/.github#221]
https://ci.eclipse.org/releng/job/AutomatedTests/job/ep433I-unit-win32-java17/85/console

```
Caused: hudson.remoting.ProxyException: java.io.IOException: java.nio.file.InvalidPathException: Illegal char <
> at index 21: C:\Users\genie.releng
eleng\workspace\AutomatedTests\ep433I-unit-win32-java17
	at hudson.Util.fileToPath(Util.java:1751)
	at hudson.FilePath.mkdirs(FilePath.java:3751)
	at hudson.FilePath$Mkdirs.invoke(FilePath.java:1416)
	at hudson.FilePath$Mkdirs.invoke(FilePath.java:1411)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3613)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:377)
	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:137)
	at java.base/java.lang.Thread.run(Thread.java:833)
Finished: FAILURE

```

**Comment by jukzi** [comment]
created https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4894

**Comment by fredg02** [comment]
Fixed.

**Comment by jukzi** [comment]
@fredg02 thanks Frederic
