### ISSUE TITLE
JDT projects are not OOmphed anymore

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/.github#226]
i tried it 2 times today and got the same result:
Following https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md i got this workspace:
![image](https://github.com/user-attachments/assets/46d8d00b-09a0-4a3a-a8b2-b9827774bc2e)
The jdt.core projects are missing in the workspace!

**Comment by jukzi** [comment]
only error in the log:

```
!ENTRY org.eclipse.jdt.core 4 4 2024-09-19 11:57:55.214
!MESSAGE Error indexing package names!
!STACK 1
Java Model Exception: Error in Java Model (code 969): C:\Users\jkubitz\.p2\pool\plugins\org.eclipse.jdt.core.tests.builder.mockcompiler_1.0.0.v20240619-0232 does not exist
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:572)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:234)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:585)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:308)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:294)
	at org.eclipse.jdt.internal.core.JavaElement.getChildren(JavaElement.java:249)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.indexPackageNames(JavaSearchNameEnvironment.java:230)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.computeClasspathLocations(JavaSearchNameEnvironment.java:219)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.computeClasspathLocations(JavaSearchNameEnvironment.java:188)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.<init>(JavaSearchNameEnvironment.java:96)
	at org.eclipse.jdt.internal.core.search.indexing.SourceIndexer.resolveDocument(SourceIndexer.java:167)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.resolveDocument(JavaSearchParticipant.java:116)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.indexResolvedDocument(IndexManager.java:679)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager$2.execute(IndexManager.java:1283)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:542)
	at java.base/java.lang.Thread.run(Thread.java:1583)
!SUBENTRY 1 org.eclipse.jdt.core 4 969 2024-09-19 11:57:55.215
!MESSAGE C:\Users\jkubitz\.p2\pool\plugins\org.eclipse.jdt.core.tests.builder.mockcompiler_1.0.0.v20240619-0232 does not exist

```

**Comment by jukzi** [comment]
no error in the setup.log:
[setup.log](https://github.com/user-attachments/files/17059455/setup.log)

**Comment by merks** [comment]
I expect that's happening because a .project file was added to the root:

![image](https://github.com/user-attachments/assets/66b17f90-ee6b-4bb3-bcfe-0a63fbaa42e6)

It was probably an accident...

@jarthana

Was this file created accidentally?

Could we remove it?  If not, I'll have to adapt the setup to accommodate it...

@jukzi 

You can work around the problem by deleting the file and performing the setup tasks again.

**Comment by Bananeweizen** [comment]
I might be side-tracking the issue: Isn't this a common failure if someone imports the git repo via import wizard (instead of letting oomph do the project import)? Can anything be done to avoid this, like having a default gitignore at the repo root?

**Comment by merks** [comment]
Yes, a .gitignore entry would help avoid the problem!

**Comment by laeubi** [comment]
> I expect that's happening because a .project file was added to the root:
> Isn't this a common failure if someone imports the git repo via import wizard

Eclipse usually searches in subfolders as well when importing projects so in general it is not an error to have a project in the root (and I often do this to get a project hierarchy displayed without working sets).

**Comment by merks** [comment]
Of course it’s not an error. The question is more, do we want it checked in? And if was checked in by accident, do we want to prevent a recurrence?
