### ISSUE TITLE
Error in disconnecting remote debugger

### ISSUE THREAD

**Issue by marekmatus** [eclipse-platform/.github#50]
I have connected remote debugger then when I click on Disconnect error occurs and the debugger reconnects.

```
eclipse.buildId=4.24.0.I20220607-0700
java.version=17.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=cs_CZ
Framework arguments:  -product org.eclipse.epp.package.jee.product -keyring /Users/marek/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch aarch64 -product org.eclipse.epp.package.jee.product -keyring /Users/marek/.eclipse_keyring

org.eclipse.core.jobs
Error
Tue Aug 16 07:23:02 CEST 2022
An internal error occurred during: "Match Job".

java.lang.NullPointerException: Cannot invoke "org.eclipse.ui.IWorkbenchWindow.getShell()" because the return value of "org.eclipse.ui.IWorkbench.getActiveWorkbenchWindow()" is null
	at org.eclipse.debug.internal.ui.DebugUIPlugin.launchInBackground(DebugUIPlugin.java:1255)
	at org.eclipse.debug.ui.DebugUITools.launch(DebugUITools.java:981)
	at org.eclipse.debug.ui.DebugUITools.launch(DebugUITools.java:787)
	at org.eclipse.m2e.internal.launch.MavenConsoleLineTracker.launchRemoteJavaApp(MavenConsoleLineTracker.java:276)
	at org.eclipse.m2e.internal.launch.MavenConsoleLineTracker.lineAppended(MavenConsoleLineTracker.java:134)
	at org.eclipse.debug.internal.ui.views.console.ConsoleLineNotifier.lineAppended(ConsoleLineNotifier.java:123)
	at org.eclipse.debug.internal.ui.views.console.ConsoleLineNotifier.matchFound(ConsoleLineNotifier.java:115)
	at org.eclipse.ui.internal.console.ConsolePatternMatcher$MatchJob.run(ConsolePatternMatcher.java:137)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by laeubi** [comment]
@marekmatus can you please try if it makes a difference if you first focus the eclipse IDE (that is click on e.g. an editor or the title-bar, ...)

Because I have seen similar issues in the past, I assume the error is when your eclipse lost focus and you directly click on the disconnect button (e.g. two monitor setup, or eclipse window made smaller, ...)

**Comment by marekmatus** [comment]
I tried it, but there is no difference if the eclipse IDE has focus or not,
the error still occurs.

út 16. 8. 2022 v 7:38 odesílatel Christoph Läubrich <
***@***.***> napsal:
