### ISSUE TITLE
Error in SDK setup

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/.github#7]
I performed my usual Update / Perform Updatetasks today but got:

```
Include Sources = true
Adding repository https://download.eclipse.org/cbi/updates/license
Adding repository https://download.eclipse.org/egit/updates
Adding repository https://download.eclipse.org/tools/orbit/downloads/latest-R
Adding repository https://download.eclipse.org/nebula/snapshot
Adding repository https://download.eclipse.org/eclipse/updates/4.24-I-builds
Adding repository https://download.eclipse.org/tools/gef/updates/milestones
Adding repository https://download.eclipse.org/modeling/emf/emf/builds/milestone/latest
Calculating requirements and dependencies.
Cannot complete the request.  Generating details.
ERROR: org.eclipse.equinox.p2.director code=10053 Cannot complete the install because one or more required items could not be found.
  at org.eclipse.oomph.targlets.internal.core.TargletContainer.forceUpdate(TargletContainer.java:838)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl$4.run(TargletTaskImpl.java:1190)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.runWithTargetPlatformService(TargetPlatformUtil.java:120)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl.perform(TargletTaskImpl.java:1050)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2369)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2394)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1651676729138
  ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: artificial_root 1.0.0.v1651676729138 requires 'org.eclipse.equinox.p2.iu; org.eclipse.platform.releng.prereqs.sdk.plain.project 0.0.0' but it could not be found

Took 7 seconds.
```

@merks any more details required?

**Comment by merks** [comment]
There is a new task to create a .project file:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/24d8664f9f4d94a4fc8cbf880b9f57ca739014c0/oomph/Platform.setup#L728-L746

But perhaps that task is running after the task to resolve the target platform!

Let me have a look...

**Comment by merks** [comment]
Yes, the order is wrong:

![image](https://user-images.githubusercontent.com/208716/166714335-3bf27a9c-634d-4de9-a6b7-60d445a87637.png)

If I moved it in the project setup then it looks like the order is correct:

![image](https://user-images.githubusercontent.com/208716/166714628-8d75c48a-b7d7-4698-8fe5-65dca3cd06a1.png)

I will commit the change right now and then you can try it.

Thanks for reporting it!!

**Comment by merks** [comment]
Oops, I forgot to add a link the issue in the PR. :-( 

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/254

Anyway, it's done now so please pull the aggregator repo and try again.

Note that with my recent changes these two projects show up in the Aggregator working group:

![image](https://user-images.githubusercontent.com/208716/166716248-4929b2d7-b37c-4df3-86d7-e9121b7d6d55.png)

I.e., the project contains the platform setup and configuration as well as the project containing the *.target used in the Tycho builds.

I'll assume it's fixed now.
