### ISSUE TITLE
org.eclipse.swt.SWTError: No more handles

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/.github#72]
My eclipse just terminated exit code 0, with a strange stacktrace in stderr with looks like a recursive logging / Exceptionhandling. just before that the number of threads seemed to raise. 
```
Error while informing user about event loop exception:
org.eclipse.swt.SWTError: No more handles
	at org.eclipse.swt.SWT.error(SWT.java:4944)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:450)
	at org.eclipse.swt.widgets.Control.createHandle(Control.java:718)
	at org.eclipse.swt.widgets.Scrollable.createHandle(Scrollable.java:145)
	at org.eclipse.swt.widgets.Composite.createHandle(Composite.java:294)
	at org.eclipse.swt.widgets.Control.createWidget(Control.java:746)
	at org.eclipse.swt.widgets.Scrollable.createWidget(Scrollable.java:160)
	at org.eclipse.swt.widgets.Control.<init>(Control.java:116)
	at org.eclipse.swt.widgets.Scrollable.<init>(Scrollable.java:85)
	at org.eclipse.swt.widgets.Composite.<init>(Composite.java:99)
	at org.eclipse.ui.internal.progress.ProgressInfoItem.<init>(ProgressInfoItem.java:192)
	at org.eclipse.ui.internal.progress.DetailedProgressViewer.createNewItem(DetailedProgressViewer.java:214)
	at org.eclipse.ui.internal.progress.DetailedProgressViewer.reorderControls(DetailedProgressViewer.java:485)
	at org.eclipse.ui.internal.progress.DetailedProgressViewer.add(DetailedProgressViewer.java:183)
	at org.eclipse.ui.internal.progress.ProgressViewerContentProvider.add(ProgressViewerContentProvider.java:136)
	at org.eclipse.ui.internal.progress.ProgressViewUpdater.update(ProgressViewUpdater.java:308)
	at org.eclipse.jface.util.Throttler.lambda$0(Throttler.java:59)
	at org.eclipse.jface.util.Throttler.lambda$1(Throttler.java:67)
	at org.eclipse.jface.util.Throttler.throttledExec(Throttler.java:94)
	at org.eclipse.ui.internal.progress.ProgressViewUpdater.addJob(ProgressViewUpdater.java:361)
	at org.eclipse.ui.internal.progress.ProgressManager.lambda$2(ProgressManager.java:378)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.eclipse.ui.internal.progress.ProgressManager.lambda$1(ProgressManager.java:378)
	at java.base/java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:671)
	at org.eclipse.ui.internal.progress.ProgressManager.notifyListeners(ProgressManager.java:378)
	at org.eclipse.jface.util.Throttler.lambda$0(Throttler.java:59)
	at org.eclipse.jface.util.Throttler.lambda$1(Throttler.java:67)
	at org.eclipse.jface.util.Throttler.throttledExec(Throttler.java:94)
	at org.eclipse.ui.internal.progress.ProgressManager.addJobInfo(ProgressManager.java:713)
	at org.eclipse.ui.internal.progress.ProgressManager$1.updateFor(ProgressManager.java:501)
	at org.eclipse.ui.internal.progress.ProgressManager$1.scheduled(ProgressManager.java:473)
	at org.eclipse.core.internal.jobs.JobListeners.sendEvent(JobListeners.java:63)
	at org.eclipse.core.internal.jobs.JobListeners.sendEvents(JobListeners.java:49)
	at org.eclipse.core.internal.jobs.JobManager.schedule(JobManager.java:1346)
	at org.eclipse.core.internal.jobs.InternalJob.schedule(InternalJob.java:392)
	at org.eclipse.core.runtime.jobs.Job.schedule(Job.java:654)
	at org.eclipse.ui.internal.ide.IDEWorkbenchErrorHandler.handle(IDEWorkbenchErrorHandler.java:125)
	at org.eclipse.ui.internal.WorkbenchErrorHandlerProxy.handle(WorkbenchErrorHandlerProxy.java:34)
	at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:217)
	at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:259)
	at org.eclipse.ui.statushandlers.StatusManager$StatusManagerLogListener.logging(StatusManager.java:328)
	at org.eclipse.core.internal.runtime.RuntimeLog.logToListeners(RuntimeLog.java:162)
	at org.eclipse.core.internal.runtime.PlatformLogWriter.logged(PlatformLogWriter.java:106)
	at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory.safeLogged(ExtendedLogReaderServiceFactory.java:107)
	at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory.logPrivileged(ExtendedLogReaderServiceFactory.java:250)
	at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory.log(ExtendedLogReaderServiceFactory.java:222)
	at org.eclipse.osgi.internal.log.ExtendedLogServiceFactory.log(ExtendedLogServiceFactory.java:102)
	at org.eclipse.osgi.internal.log.LoggerImpl.log(LoggerImpl.java:88)
	at org.eclipse.osgi.internal.log.LoggerImpl.log(LoggerImpl.java:80)
	at org.eclipse.osgi.internal.log.LoggerImpl.log(LoggerImpl.java:76)
	at org.eclipse.core.internal.runtime.PlatformLogWriter.logging(PlatformLogWriter.java:47)
	at org.eclipse.core.internal.runtime.RuntimeLog.log(RuntimeLog.java:100)
	at org.eclipse.core.internal.jobs.JobListeners.handleException(JobListeners.java:91)
	at org.eclipse.core.internal.jobs.JobListeners.sendEvent(JobListeners.java:65)
	at org.eclipse.core.internal.jobs.JobListeners.sendEvents(JobListeners.java:49)
	at org.eclipse.core.internal.jobs.JobManager.schedule(JobManager.java:1346)
	at org.eclipse.core.internal.jobs.InternalJob.schedule(InternalJob.java:392)
	at org.eclipse.core.runtime.jobs.Job.schedule(Job.java:654)
	at org.eclipse.ui.internal.ide.IDEWorkbenchErrorHandler.handle(IDEWorkbenchErrorHandler.java:125)
	at org.eclipse.ui.internal.WorkbenchErrorHandlerProxy.handle(WorkbenchErrorHandlerProxy.java:34)
	at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:217)
	at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:259)
	at org.eclipse.ui.statushandlers.StatusManager$StatusManagerLogListener.logging(StatusManager.java:328)
	at org.eclipse.core.internal.runtime.RuntimeLog.logToListeners(RuntimeLog.java:162)
	at org.eclipse.core.internal.runtime.PlatformLogWriter.logged(PlatformLogWriter.java:106)
	
... many repetitions

	at org.eclipse.core.internal.runtime.PlatformLogWriter.logged(PlatformLogWriter.java:106)
	at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory.safeLogged(ExtendedLogReaderServiceFactory.java:107)
	at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory.logPrivileged(ExtendedLogReaderServiceFactory.java:250)
	at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory.log(ExtendedLogReaderServiceFactory.java:222)
	at org.eclipse.osgi.internal.log.ExtendedLogServiceFactory.log(ExtendedLogServiceFactory.java:102)
	at org.eclipse.osgi.internal.log.LoggerImpl.log(LoggerImpl.java:88)
	at org.eclipse.osgi.internal.log.LoggerImpl.log(LoggerImpl.java:80)
	at org.eclipse.osgi.internal.log.LoggerImpl.log(LoggerImpl.java:76)
	at org.eclipse.core.internal.runtime.PlatformLogWriter.logging(PlatformLogWriter.java:47)
	at org.eclipse.core.internal.runtime.RuntimeLog.log(RuntimeLog.java:100)
	at org.eclipse.core.internal.jobs.JobListeners.handleException(JobListeners.java:91)
	at org.eclipse.core.internal.jobs.JobListeners.sendEvent(JobListeners.java:65)
	at org.eclipse.core.internal.jobs.JobListeners.sendEvents(JobListeners.java:49)
	at org.eclipse.core.internal.jobs.JobManager.schedule(JobManager.java:1346)
	at org.eclipse.core.internal.jobs.InternalJob.schedule(InternalJob.java:392)
	at org.eclipse.core.runtime.jobs.Job.schedule(Job.java:654)
	at org.eclipse.ui.internal.ide.IDEWorkbenchErrorHandler.handle(IDEWorkbenchErrorHandler.java:125)
	at org.eclipse.ui.internal.WorkbenchErrorHandlerProxy.handle(WorkbenchErrorHandlerProxy.java:34)
	at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:217)
	at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:259)
	at org.eclipse.ui.statushandlers.StatusManager$StatusManagerLogListener.logging(StatusManager.java:328)
	at org.eclipse.core.internal.runtime.RuntimeLog.logToListeners(RuntimeLog.java:162)
	at org.eclipse.core.internal.runtime.PlatformLogWriter.logged(PlatformLogWriter.java:106)
	at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory.safeLogged(ExtendedLogReaderServiceFactory.java:107)
	at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory.logPrivileged(ExtendedLogReaderServiceFactory.java:250)
	at org.eclipse.osgi.internal.log.ExtendedLogReaderServiceFactory.log(ExtendedLogReaderServiceFactory.java:222)
	at org.eclipse.osgi.internal.log.ExtendedLogServiceFactory.log(ExtendedLogServiceFactory.java:102)
	at org.eclipse.osgi.internal.log.LoggerImpl.log(LoggerImpl.java:88)
	at org.eclipse.osgi.internal.log.LoggerImpl.log(LoggerImpl.java:80)
	at org.eclipse.osgi.internal.log.LoggerImpl.log(LoggerImpl.java:76)
	at org.eclipse.core.internal.runtime.PlatformLogWriter.logging(PlatformLogWriter.java:47)
	at org.eclipse.core.internal.runtime.RuntimeLog.log(RuntimeLog.java:100)
	at org.eclipse.core.internal.jobs.JobListeners.handleException(JobListeners.java:91)
	at org.eclipse.core.internal.jobs.JobListeners.sendEvent(JobListeners.java:65)
Dialog open exception:
org.eclipse.swt.SWTError: No more handles
	at org.eclipse.swt.SWT.error(SWT.java:4944)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:450)
	at org.eclipse.swt.widgets.Control.createHandle(Control.java:718)
	at org.eclipse.swt.widgets.Scrollable.createHandle(Scrollable.java:145)
	at org.eclipse.swt.widgets.Composite.createHandle(Composite.java:294)
	at org.eclipse.swt.widgets.Control.createWidget(Control.java:746)
	at org.eclipse.swt.widgets.Scrollable.createWidget(Scrollable.java:160)
	at org.eclipse.swt.widgets.Control.<init>(Control.java:116)
	at org.eclipse.swt.widgets.Scrollable.<init>(Scrollable.java:85)
	at org.eclipse.swt.widgets.Composite.<init>(Composite.java:99)
	at org.eclipse.jface.dialogs.IconAndMessageDialog.createButtonBar(IconAndMessageDialog.java:170)
	at org.eclipse.jface.dialogs.IconAndMessageDialog.createDialogAndButtonArea(IconAndMessageDialog.java:229)
	at org.eclipse.jface.dialogs.IconAndMessageDialog.createContents(IconAndMessageDialog.java:207)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
	at org.eclipse.ui.internal.ide.dialogs.InternalErrorDialog.open(InternalErrorDialog.java:81)
	at org.eclipse.ui.internal.ide.IDEWorkbenchErrorHandler.openQuestionDialog(IDEWorkbenchErrorHandler.java:188)
	at org.eclipse.ui.internal.ide.IDEWorkbenchErrorHandler.handleException(IDEWorkbenchErrorHandler.java:147)
	at org.eclipse.ui.internal.ide.IDEWorkbenchErrorHandler$1.runInUIThread(IDEWorkbenchErrorHandler.java:115)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:95)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4043)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3648)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

```

**Comment by jukzi** [comment]
The logfiles did overflow with logentries like
```
!ENTRY org.eclipse.ui 4 4 2022-10-14 12:08:07.912
!MESSAGE An internal error has occurred.
!STACK 0
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:450)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:369)
	at org.eclipse.swt.widgets.Label.setText(Label.java:391)
	at org.eclipse.ui.internal.ide.IDEWorkbenchErrorHandler$FatalErrorDialog.updateMessage(IDEWorkbenchErrorHandler.java:290)
	at org.eclipse.ui.internal.ide.IDEWorkbenchErrorHandler.handleException(IDEWorkbenchErrorHandler.java:144)
	at org.eclipse.ui.internal.ide.IDEWorkbenchErrorHandler$1.runInUIThread(IDEWorkbenchErrorHandler.java:115)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:95)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4043)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3648)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.block(ModalContext.java:166)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:368)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:470)
	at org.eclipse.ui.internal.progress.ProgressMonitorJobsDialog.run(ProgressMonitorJobsDialog.java:230)
	at org.eclipse.ui.internal.ide.application.IDEWorkbenchAdvisor.disconnectFromWorkspace(IDEWorkbenchAdvisor.java:560)
	at org.eclipse.ui.internal.ide.application.IDEWorkbenchAdvisor$2.run(IDEWorkbenchAdvisor.java:367)
	at org.eclipse.ui.internal.ide.application.IDEWorkbenchAdvisor.postShutdown(IDEWorkbenchAdvisor.java:388)
	at org.eclipse.ui.internal.Workbench.shutdown(Workbench.java:2942)
	at org.eclipse.ui.internal.Workbench.busyClose(Workbench.java:1124)
	at org.eclipse.ui.internal.Workbench.lambda$4(Workbench.java:1392)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.internal.Workbench.close(Workbench.java:1392)
	at org.eclipse.ui.internal.WorkbenchConfigurer.emergencyClose(WorkbenchConfigurer.java:148)
	at org.eclipse.ui.internal.ide.IDEWorkbenchErrorHandler.closeWorkbench(IDEWorkbenchErrorHandler.java:242)
	at org.eclipse.ui.internal.ide.IDEWorkbenchErrorHandler.handleException(IDEWorkbenchErrorHandler.java:148)
	at org.eclipse.ui.internal.ide.IDEWorkbenchErrorHandler$1.runInUIThread(IDEWorkbenchErrorHandler.java:115)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:95)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4043)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3648)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

!ENTRY org.eclipse.ui 4 4 2022-10-14 12:08:07.913
!MESSAGE An internal error has occurred.
!STACK 0
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:450)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:369)
	at org.eclipse.swt.widgets.Label.setText(Label.java:391)
	at org.eclipse.ui.internal.ide.IDEWorkbenchErrorHandler$FatalErrorDialog.updateMessage(IDEWorkbenchErrorHandler.java:290)
```

**Comment by iloveeclipse** [comment]
1) This should be SWT issue
2) What was the **first** error logged?

**Comment by jukzi** [comment]
I can not see the first error, because all logfiles only contain that "emergencyClose" exception over and over.
I doubt it's SWT because the root reason seems to be the recursive exception logging, i  don't now which module should prevent that.

**Comment by jukzi** [comment]
interesting, the UI even detected that i was an recursive exception:
https://github.com/eclipse-platform/eclipse.platform.ui/blob/1ea3997919429ee91303051c814ade6ad0f65825/bundles/org.eclipse.ui.ide/src/org/eclipse/ui/internal/ide/IDEWorkbenchErrorHandler.java#L145

**Comment by jukzi** [comment]
"No more handles" keeps happening after editing like a hundret MANIFEST.MF with PDE editor - i have left all editors open.
first exception is:

```
!ENTRY org.eclipse.ui 4 0 2022-10-14 14:17:57.183
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTError: No more handles
	at org.eclipse.swt.SWT.error(SWT.java:4944)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:450)
	at org.eclipse.swt.widgets.Control.createHandle(Control.java:718)
	at org.eclipse.swt.widgets.Label.createHandle(Label.java:188)
	at org.eclipse.swt.widgets.Control.createWidget(Control.java:746)
	at org.eclipse.swt.widgets.Control.<init>(Control.java:116)
	at org.eclipse.swt.widgets.Label.<init>(Label.java:106)
	at org.eclipse.ui.texteditor.StatusLineContributionItem.fill(StatusLineContributionItem.java:166)
	at org.eclipse.jface.action.SubContributionItem.fill(SubContributionItem.java:61)
	at org.eclipse.jface.action.SubContributionItem.fill(SubContributionItem.java:61)
	at org.eclipse.jface.action.StatusLineManager.update(StatusLineManager.java:290)
	at org.eclipse.ui.internal.WorkbenchWindow.updateActionBars(WorkbenchWindow.java:2496)
	at org.eclipse.ui.internal.WWinActionBars.updateActionBars(WWinActionBars.java:125)
	at org.eclipse.ui.SubActionBars.updateActionBars(SubActionBars.java:602)
	at org.eclipse.pde.internal.ui.editor.PDEFormTextEditorContributor.setSourceActionBarsActive(PDEFormTextEditorContributor.java:155)
	at org.eclipse.pde.internal.ui.editor.PDEFormTextEditorContributor.setActivePage(PDEFormTextEditorContributor.java:196)
	at org.eclipse.ui.part.MultiPageEditorPart.pageChange(MultiPageEditorPart.java:807)
	at org.eclipse.ui.forms.editor.FormEditor.pageChange(FormEditor.java:501)
	at org.eclipse.pde.internal.ui.editor.PDEFormEditor.pageChange(PDEFormEditor.java:255)
	at org.eclipse.ui.part.MultiPageEditorPart.setActivePage(MultiPageEditorPart.java:1030)
	at org.eclipse.ui.forms.editor.FormEditor.setActivePage(FormEditor.java:612)
	at org.eclipse.ui.forms.editor.FormEditor.setActivePage(FormEditor.java:518)
	at org.eclipse.pde.internal.ui.editor.PDEFormEditor.setActivePage(PDEFormEditor.java:733)
	at org.eclipse.pde.internal.ui.editor.PDEFormEditor.gotoMarker(PDEFormEditor.java:646)
	at org.eclipse.ui.ide.IDE.gotoMarker(IDE.java:321)
	at org.eclipse.search.internal.ui.text.EditorOpener.showWithMarker(EditorOpener.java:138)
	at org.eclipse.search.internal.ui.text.EditorOpener.openAndSelect(EditorOpener.java:70)
	at org.eclipse.search.ui.text.AbstractTextSearchViewPage.openAndSelect(AbstractTextSearchViewPage.java:449)
	at org.eclipse.search.internal.ui.text.FileSearchPage.showMatch(FileSearchPage.java:230)
	at org.eclipse.search.ui.text.AbstractTextSearchViewPage$3.run(AbstractTextSearchViewPage.java:928)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.search.ui.text.AbstractTextSearchViewPage.showMatch(AbstractTextSearchViewPage.java:931)
	at org.eclipse.search.ui.text.AbstractTextSearchViewPage.showCurrentMatch(AbstractTextSearchViewPage.java:996)
	at org.eclipse.search.ui.text.AbstractTextSearchViewPage.gotoNextMatch(AbstractTextSearchViewPage.java:961)
	at org.eclipse.search.ui.text.AbstractTextSearchViewPage.handleOpen(AbstractTextSearchViewPage.java:1417)
	at org.eclipse.search.internal.ui.text.FileSearchPage.handleOpen(FileSearchPage.java:251)
	at org.eclipse.search.ui.text.AbstractTextSearchViewPage$2.open(AbstractTextSearchViewPage.java:755)
	at org.eclipse.ui.OpenAndLinkWithEditorHelper$InternalListener.open(OpenAndLinkWithEditorHelper.java:48)
	at org.eclipse.jface.viewers.StructuredViewer$2.run(StructuredViewer.java:800)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.StructuredViewer.fireOpen(StructuredViewer.java:797)
	at org.eclipse.jface.viewers.StructuredViewer.handleOpen(StructuredViewer.java:1116)
	at org.eclipse.jface.util.OpenStrategy.fireOpenEvent(OpenStrategy.java:296)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:331)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4068)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

```
